export default [
  {
    id: "4",
    title: "Skilled E-Learning",
    category: "Frontend Mentor",
    description:
      "Landing page de práctica para empresa que brinda servicios educativos online.",
    img: "/card_imgs/skilled_elearning.png",
    alt: "Ilustración de cómo se ve el sitio web en una notebook.",
    tools: ["HTML", "SASS"],
    github: "https://github.com/Dev-Santi/challenges--Skilled-elearning",
    website: "https://dev-santi.github.io/challenges--Skilled-elearning",
  },
  {
    id: "2",
    title: "Single Page Portfolio",
    category: "Frontend Mentor",
    description: "Portafolio web sencillo para un diseñador.",
    img: "/card_imgs/portfolio.png",
    alt: "Ilustración de cómo se ve el sitio web en una notebook.",
    tools: ["HTML", "CSS", "JavaScript"],
    github: "https://github.com/Dev-Santi/challenges--Single-page-portfolio",
    website: "https://dev-santi.github.io/challenges--Single-page-portfolio",
  },
  {
    id: "3",
    title: "Brascesco & Larrosa",
    category: "Curso",
    description:
      "Proyecto final para curso de Desarrollador Web en la academia CoderHouse. Se trata de un sitio web para un estudio jurídico.",
    img: "/card_imgs/brascesco_larrosa.png",
    alt: "Ilustración de cómo se ve el sitio web en una notebook.",
    tools: ["HTML", "SASS", "BootStrap"],
    github: "https://github.com/Dev-Santi/coderhouse--BrascescoyLarrosa",
    website:
      "https://dev-santi.github.io/coderhouse--BrascescoyLarrosa/index.html",
  },
  {
    id: "5",
    title: "News Homepage",
    category: "Frontend Mentor",
    description: "Proyecto de desafío proporcionado por Frontend Mentor.",
    img: "/card_imgs/news_homepage.png",
    alt: "Ilustración de cómo se ve el sitio web en una notebook.",
    tools: ["HTML", "CSS", "JavaScript"],
    github: "https://github.com/Dev-Santi/challenges--News-Homepage",
    website: "https://dev-santi.github.io/challenges--News-Homepage",
  } /* 
  {
    id: "1",
    title: "Crips",
    category: "working on progress",
    description: "Aplicación web para una tienda de ropa.",
    img: "/card_imgs/crisp.png",
    alt: "Ilustración de cómo se ve el sitio web en una notebook.",
    tools: ["NextJs", "MongoDB", "Tailwind"],
    github: "https://github.com/Dev-Santi/-Crisp-ecommerce",
    website: "https://crisp-ecommerce.vercel.app/",
  }, */,
];
