export default [
    {
        id: "8",
        title: "Justo a Tiempo",
        description:
            "Aplicación web Full Stack que tiene como objetivo principal el facilitar una gestión eficiente de los plazos legales y administrativos en Uruguay.",
        img: "/card_imgs/justo_a_tiempo.png",
        alt: "Ilustración de cómo se ve el sitio web en una notebook.",
        tools: [
            "Next.js",
            "MongoDB",
            "Auth.js",
            "Node.js",
            "TypeScript",
            "Tailwind",
        ],
        github: "https://github.com/Dev-Santi/LegalDateNextjs",
        website: "https://www.justoatiempo.pro",
    },
    {
        id: "7",
        title: "Taller Mecánico",
        description:
            "Aplicación web para un taller de mecánicos. Muestra de servicios, métodos de contacto a través de api, google maps.",
        img: "/card_imgs/taller.png",
        alt: "Ilustración de cómo se ve el sitio web en una notebook.",
        tools: [
            "TypeScript",
            "Next.js",
            "Node.js",
            "Tailwind",
            "Animate.css",
            "Maps",
        ],
        github: "https://github.com/Dev-Santi/Taller-mec-nico-Next.js",
        website: "https://taller-mecanico-next-js.vercel.app/",
    },
    {
        id: "6",
        title: "Restaurante",
        description:
            "Aplicación web para un restaurante, con la funcionalidad de poder hacer reservas desde el sitio o descargar el menu del día.",
        img: "/card_imgs/restaurant.png",
        alt: "Ilustración de cómo se ve el sitio web en una notebook.",
        tools: ["Next.js", "Node.js", "Tailwind"],
        github: "https://github.com/Dev-Santi/Restaurant-next.js",
        website: "https://rest-dev-santi.vercel.app/",
    },
    {
        id: "5",
        title: "Portafolio para Fotógrafos",
        description:
            "Galería web completa para fotógrafos y/o diseñadores que deseen tener su propio espacio para mostrar su trabajo.",
        img: "/card_imgs/portfolio_photo.png",
        alt: "Ilustración de cómo se ve el sitio web en una notebook.",
        tools: ["Next.js", "Tailwind"],
        github: "https://github.com/Dev-Santi/photographer_portfolio",
        website: "https://photographer-portfolio-smoky.vercel.app/",
    },
    {
        id: "4",
        title: "Estetica y bienestar 💅",
        description:
            "Espacio web para gente que se dedica al cuidado de las uñas, donde poder mostrar una galería de fotos, reviews, catálogos e información de contacto.",
        img: "/card_imgs/manicura_site.png",
        alt: "Ilustración de cómo se ve el sitio web en una notebook.",
        tools: ["Next.js", "Tailwind"],
        github: "https://github.com/Dev-Santi/manicura-site",
        website: "https://manicura-site.vercel.app/",
    },

    {
        id: "3",
        title: "Portafolio para diseñadores",
        description: "Portada para un portafolio web destinado a diseñadores.",
        img: "/card_imgs/portfolio.png",
        alt: "Ilustración de cómo se ve el sitio web en una notebook.",
        tools: ["HTML", "CSS", "JavaScript"],
        github: "https://github.com/Dev-Santi/challenges--Single-page-portfolio",
        website:
            "https://dev-santi.github.io/challenges--Single-page-portfolio",
    },
    {
        id: "2",
        title: "Brascesco & Larrosa",
        description: "Sitio web para un estudio jurídico ficticio.",
        img: "/card_imgs/brascesco_larrosa.png",
        alt: "Ilustración de cómo se ve el sitio web en una notebook.",
        tools: ["HTML", "SASS", "BootStrap"],
        github: "https://github.com/Dev-Santi/coderhouse--BrascescoyLarrosa",
        website:
            "https://dev-santi.github.io/coderhouse--BrascescoyLarrosa/index.html",
    },
    {
        id: "1",
        title: "News Homepage",
        description: "Página principal de un sitio web de noticias.",
        img: "/card_imgs/news_homepage.png",
        alt: "Ilustración de cómo se ve el sitio web en una notebook.",
        tools: ["HTML", "CSS", "JavaScript"],
        github: "https://github.com/Dev-Santi/challenges--News-Homepage",
        website: "https://dev-santi.github.io/challenges--News-Homepage",
    },
    {
        id: "0",
        title: "Skilled E-Learning",
        description:
            "Landing page para empresa ficticia que brinda servicios educativos online.",
        img: "/card_imgs/skilled_elearning.png",
        alt: "Ilustración de cómo se ve el sitio web en una notebook.",
        tools: ["HTML", "SASS"],
        github: "https://github.com/Dev-Santi/challenges--Skilled-elearning",
        website: "https://dev-santi.github.io/challenges--Skilled-elearning",
    },
];
